paths:
  subdomains: ./wordlists/wordlist.txt
  resolvers: ./wordlists/resolvers.txt
  backup_login: ./wordlists/backup_login.txt
  js-smart-fuzzing: ~/wordlistjs.txt
  output_dir: ./output
  nuclei_templates: /path/to/nuclei-templates
settings:
  threads: 10
  timeout: 30
tools:
  linkfinder: toolssparky/linkfinder/LinkFinder.py
  secretfinder: toolssparky/SecretFinder/SecretFinder.py
